# Build dexed with JUCE buidls

trigger:
  - main

pr:
  - main

jobs:

  - job: Test
    strategy:
      matrix:
        mac:
          imageName: 'macos-10.15'
          isMac: True
        win:
          imageName: 'windows-2019'
          isWindows: True
        lin:
          imageName: 'ubuntu-20.04'
          isLinux: True

    pool:
      vmImage: $(imageName)

    steps:
      - checkout: self
        fetchDepth: 1

      - bash: |
          cmake -Bbuild -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release
          ./build/test-binary/sst-filters-tests
        displayName: Run tests with cmake

  - job: Examples
    strategy:
      matrix:
        mac:
          imageName: 'macos-10.15'
          cmakeArguments: "-DCMAKE_BUILD_TYPE=Release -DSST_FILTERS_BUILD_EXAMPLES=ON"
          isMac: True
        mac-arm:
          imageName: 'macos-10.15'
          cmakeArguments: "-GXcode -DCMAKE_BUILD_TYPE=Release -DSST_FILTERS_BUILD_EXAMPLES=ON -D\"CMAKE_OSX_ARCHITECTURES=arm64\""
          isMac: True
        win:
          imageName: 'windows-2019'
          cmakeArguments: "-DCMAKE_BUILD_TYPE=Release -DSST_FILTERS_BUILD_EXAMPLES=ON"
          isWindows: True
        lin:
          imageName: 'ubuntu-20.04'
          cmakeArguments: "-DCMAKE_BUILD_TYPE=Release -DSST_FILTERS_BUILD_EXAMPLES=ON"
          isLinux: True

    pool:
      vmImage: $(imageName)

    steps:
      - checkout: self
        fetchDepth: 1

      - bash: cmake -Bbuild $(cmakeArguments)
        displayName: Run cmake configure

      - bash: cmake --build build --config Release --target filter_plot_tool
        displayName: Build filter_plot_tool
