name: Tests and Examples

on:
  pull_request:
    branches:
      - main

jobs:
  build_tests:
    name: Test ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        include:
          - os: ubuntu-latest
            name: linux
            testExe: build/tests/sst-filters-tests
          - os: macos-latest
            name: mac
            testExe: build/tests/sst-filters-tests
          - os: windows-latest
            name: win
            testExe: build/tests/Release/sst-filters-tests.exe

    steps:

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build Smoke test
        run: |
          cmake -S . -B ./build -DCMAKE_BUILD_TYPE=Release -DSST_FILTERS_BUILD_TESTS=TRUE -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64"
          cmake --build ./build --config Release

      - name: Run Smoke Test
        run: |
          ls ${{ matrix.testExe }}
          ${{ matrix.testExe }}

  build_examples:
    name: Examples ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        include:
          - os: ubuntu-latest
            name: linux
            testExe: build/sst-filters-tests
          - os: macos-latest
            name: mac
            testExe: build/sst-filters-tests
          - os: windows-latest
            name: win
            testExe: build/Release/sst-filters-tests.exe

    steps:

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Prepare for JUCE
        uses: surge-synthesizer/sst-githubactions/prepare-for-juce@main
        with:
          os: ${{ runner.os }}

      - name: Build Examples
        run: |
          cmake -Bbuild -DCMAKE_BUILD_TYPE=Debug -DSST_FILTERS_BUILD_EXAMPLES=ON
          cmake --build build --config Debug --target filter_plot_tool
          cmake --build build --config Debug --target FiltersPlugin_VST3
